### PR TITLE
Admin menu

### PR DESCRIPTION
**Pull request by SpacePuddles**
Please Change this to fix it

### CODE REVIEW

**Comment by SpacePuddles** [comment]
nice you dudes

**Comment by SpacePuddles** [comment]
check this shizzit out LOL I'M SO COOL LOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOL
#lolololololol

**Comment by SpacePuddles** [comment]
I hope this makes your day

**Comment by SpacePuddles** [comment]
shizit

**Comment by SpacePuddles** [comment]
yyufyufyughgyu`ijjioihogfy7idraerawawe

**Comment by SpacePuddles** [comment]
lol

**Comment by SpacePuddles** [comment]
that was caleb

**Comment by SpacePuddles** [comment]
I am so quirky

**Comment by ghost** [comment]
k

**Comment by AFreakinBanana** [comment]
tea why

**Comment by SpacePuddles** [comment]
tea why not

**Comment by SpacePuddles** [comment]
why is my profile picture a cool bear, and mikes is a mustached man in a hat

**Pull request merged**
